<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <RootNamespace>Demonware.Service.LegacyLobby</RootNamespace>
    <AssemblyName>Demonware.LegacyLobby</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Demonware.Core\Demonware.Core.csproj" />
    <ProjectReference Include="..\..\Demonware.Legacy\Demonware.Legacy.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
  </ItemGroup>
</Project>

